### ISSUE TITLE
Color classes missing?

### ISSUE THREAD

**Issue by russellquinn** [Nerian/bootstrap-wysihtml5-rails#107]
The editor uses CSS classes to markup the text, but these aren't defined?

wysiwyg-color-navy
wysiwyg-color-red
etc.

**Comment by Nerian** [comment]
Yes, I see them in the javascript, but they don't appear to be anywhere in the css

**Comment by Nerian** [comment]
And I can confirm that if you initialize the text like this:

```
$('.textarea').wysihtml5({toolbar: { color: true } });
```

The text that you give a color to is not colored.

I found this issue in the source repo:

https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/issues/68

It mentions that you need to include an external stylesheet, though no such stylesheet is provided from that repository or this one.

Including an external stylesheet is the path because the editor is loaded in an iframe, no stylesheet defined in the main html document is going to be available, or affect, the contents in the iframe. Defining the colors in the main css would have no effect; we need an external stylesheet. I believe one should be provided.

@Waxolunist What do you think is the best way to do this?

We could follow the path of the external stylesheet, but maybe there is a more friendly approach. I was thinking on hardcoding the colors in the javascript, so that it just works. We can still support an external  stylesheet if the user really wants to use their own color palette. 

So the default would be to use the hardcoded color definitions, but the user included an external javascript via the `stylesheets: ["{{ STATIC_URL }}css/bootstrap3-wysiwyg5-color.css"`parameter it would use that instead of the hardcoded one.

Thoughts?

**Comment by russellquinn** [comment]
Yeah, I fixed it by including an external stylesheet with my own definitions. The colors should really be hardcoded.

**Comment by ryan2johnson9** [comment]
We use the editor to create html that we send out of our project, e.g. as a letter via email etc. So the wysiwyg-color- classes are no good for us. I have to use regular expressions to add inline color styles to elements with these classes.

**Comment by russellquinn** [comment]
How you style the HTML on the front-end is a separate concern. We're discussing how it's styled in the WYSIWYG editor itself.

**Comment by Nerian** [comment]
@russellquinn 

I think it would be useful to provide the colors stylesheet in this gem – at least until this matter is solved by hardcoding it in bootstrap-wysihtml5 itself . 

If you would like to make a Pull Request it would be welcomed.

@ryan2johnson9 I assume you are creating an email using text? Why don't you use an HTML template? May be more simple.

**Comment by ryan2johnson9** [comment]
Why are the colours treated differently from the other wysisyg aspects. I mean, all other buttons result in html than can be displayed outside of the Wysiwyg editor. Why not use inline colour styles on the elements rather than adding special colour classes? There is probably a good reason, I am just interested.

@Nerian, thanks for the recommendation on the templates, I do not know much about them and will look into them. Wysihtml5 is very handy as it provides so much flexibility which we need in our letters, and we also use it for some html strings we send to an API for display on their website, so good to have the consistency across our site..

**Comment by russellquinn** [comment]
Done: https://github.com/Nerian/bootstrap-wysihtml5-rails/pull/112
