### ISSUE TITLE
Problem when clicking on to change link

### ISSUE THREAD

**Issue by Rubioli** [Nerian/bootstrap-wysihtml5-rails#145]
Adding links from toolbar is not a issue BUT when I click on the link again to edit it. The modal does not "fade out" and making problem.

**Comment by mmeeoorroo** [comment]
I have the same problem

**Comment by mikevoets** [comment]
Me too.

**Comment by mmeeoorroo** [comment]
I think it is caused by an infinite loop: focus/click/press key on the link in the editor -> trigger modal -> close modal -> auto focus back to the editor -> the cursor still on the link -> trigger the modal again -> loop.

 I temporarily fixed it here https://github.com/thinkei/bootstrap-wysihtml5-rails/. I fixed by disable focus and keyup events for "Link command".

**Comment by mikevoets** [comment]
I also have the same problem.

**Comment by Rubioli** [comment]
@mmeeoorroo Could please tell me how can I do the same you did?
Thanks

**Comment by mmeeoorroo** [comment]
@Rubioli my fix is in the latest commit on this branch https://github.com/Thinkei/bootstrap-wysihtml5-rails/commits/cannot-edit-link. Fork it and install the gem from your repo, branch `cannot-edit-link`

```
#Gemfile
gem 'bootstrap-wysihtml5-rails', git: 'https://github.com/thinkei/bootstrap-wysihtml5-rails', branch: 'cannot-edit-link'
```

**Comment by Rubioli** [comment]
Thanks :) 👍

**Comment by buncismamen** [comment]
@mmeeoorroo hi, can you make a pull request to master?
